### PR TITLE
Create RequestStorage.cfc

### PR DESCRIPTION
**Pull request by murphydan**
Just like the other storages but for the Request scope.

### CODE REVIEW

**Comment by bdw429s** [comment]
Thanks @murphydan !

**Comment by bdw429s** [comment]
https://ortussolutions.atlassian.net/browse/CCM-39

**Comment by elpete** [comment]
Hey, @bdw429s.  How often does this module get published?  We'd use the development version, but I'm not sure how to specify the folder since the repo is more than just the module.

**Comment by bdw429s** [comment]
Good question, I'm not sure.  That's a question for @lmajano and is why I like my Git repo to just be the module so I  point to it with the Git endpoint :)  

Figuring out release cycles was something I was going to chat to @lmajano about when he's back.  It used to be easy when we only had 1 or 2 repos.  Now we have roughly 7 thousand and it's really hard to track which random projects have commits on dev that are waiting to be released.  I'm actually curious if we can script a report that shows all the repos who's dev branch is ahead of master (somehow ignoring the obligatory new version bump)

**Comment by lmajano** [comment]
Hard to track.  I am doing micro-releases now for the modules. Basically, any pull request that comes in or new feature.  We are slowly adding auto-publishing to the modules. So all we need is to  do a pull, see if it works, then merge into master and it self-publishes.

**Comment by lmajano** [comment]
Merged and published: https://www.forgebox.io/view/cbstorages

**Pull request merged**
