### PR TITLE
Hotfix/ccm 54 session storage fix

### PR DESCRIPTION
**Pull request by sjdaniels**

### CODE REVIEW

**Comment by sjdaniels** [comment]
This bug only revealed itself when applicationStorage was accessed before sessionStorage. That's why your tests were all passing. Not sure if there's a point to adding a test for this.

**Comment by bdw429s** [comment]
https://ortussolutions.atlassian.net/browse/CCM-54

**Comment by lmajano** [comment]
I will add a test

**Comment by lmajano** [comment]
but in reality, it was due to the new refactorings

**Pull request merged**
